fix esteira

diff --git a/.github/workflows/feature-pr-develop.yml b/.github/workflows/feature-pr-develop.yml
--- a/.github/workflows/feature-pr-develop.yml
+++ b/.github/workflows/feature-pr-develop.yml
@@ -6,10 +6,48 @@ on:
       - 'feature/**'
     
 jobs:
+  sonar_analyse:
+    name:  Build  and  analyze Sonarqube /develop
+    runs-on:  ubuntu-latest 
+    steps:
+      - uses: actions/checkout@v4
+        with: 
+          fetch-depth:  0   # Shallow clones should be disabled for a better relevance of analysis 
+      - name: Set up JDK 21 
+        uses: actions/setup-java@v4 
+        with: 
+          java-version:  21 
+          distribution:  'zulu'  # Alternative distribution options are available.
+      - name: Cache de pacotes SonarQube
+        uses: actions/cache@v4
+        with: 
+          path: ~/.sonar/cache 
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar 
+      - name: Cache de pacotes Maven 
+        uses: actions/cache@v4
+        with: 
+          path: ~/.m2/
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} 
+          restore-keys: ${{ runner.os }}-m2
+      - name: Corrigir encoding de arquivos properties
+        run: |
+          find . -path "*/src/main/resources/*.properties" -type f -exec sh -c 'iconv -f ISO-8859-1 -t UTF-8 "$1" > "$1.tmp" && mv "$1.tmp" "$1"' _ {} \; || true
+ 
+  
+      - name: Build and analyze Sonar
+        env: 
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
+
+        run: |
+          POM_FILE=$(find . -name "pom.xml" -not -path "*/target/*" -maxdepth 2 | head -n 1)
+          if [ -z "$POM_FILE" ]; then echo "pom.xml not found"; exit 1; fi
+          mvn -f "$POM_FILE" -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=TechFiap_soat-tech-challenge4-app-customer
+
 
   create_pull_request:
     runs-on: ubuntu-latest
-    
+    needs: sonar_analyse
     permissions:
       pull-requests: write
       contents: write
